"""added item_models

Revision ID: 8e826c9724e6
Revises: 23c102a132d3
Create Date: 2026-01-21 14:42:17.516343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e826c9724e6'
down_revision: Union[str, Sequence[str], None] = '23c102a132d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('item_model', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'item_model')
    # ### end Alembic commands ###
