"""deleted item_models

Revision ID: d442aeea36af
Revises: 8e826c9724e6
Create Date: 2026-01-21 14:46:21.188846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd442aeea36af'
down_revision: Union[str, Sequence[str], None] = '8e826c9724e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'item_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('item_model', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
